import {img} from "@/lib/images";
import Parallax from "@/components/Parallax";
const V=[["Trust & Transparency","Clear plans and honest pricing, with no surprises."],["Local Expertise","Certified guides who know every hidden gem."],["Customization","Every trip is built around you."],["Care","24/7 support from first call to drop-off."]];
const F=[["Can I customize a package?","Yes. Every tour is private and flexible: duration, hotels, activities and pickup points can all be changed."],["What is included in the tours?","A private air-conditioned car with an experienced driver, plus local guides where listed in the itinerary."],["How do I book?","Call or WhatsApp us, or send an enquiry from the Contact page."]];
export default function A(){return(<main>
<Parallax img={img("taj",1800)} priority h="min-h-[40vh]"><h1 className="!text-white text-4xl sm:text-5xl">About Us</h1></Parallax>
<section className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-16 md:grid-cols-2"><div><p className="text-sm font-semibold text-saffron">About Tripsthan</p><h2 className="text-3xl">Authentic India, Where Charm Knows No Bounds</h2>
<p className="mt-4">Tripsthan is your gateway to India: a travel company dedicated to creating unforgettable, memorable holiday experiences at reasonable prices.</p>
<div className="mt-8 grid grid-cols-3 gap-4">{[["5,000+","Happy travelers"],["200+","Tour packages"],["4.9","Average rating"]].map(([n,l])=><div key={l}><b className="font-head text-2xl text-saffron">{n}</b><p className="text-xs">{l}</p></div>)}</div></div>
<div className="h-64 rounded-card bg-dark bg-cover bg-center shadow-card md:h-80" style={{backgroundImage:"url("+img("travel",1200)+")"}}/></section>
<section className="bg-warm"><div className="mx-auto max-w-3xl px-5 py-16 text-center"><h2 className="text-3xl">Our Story</h2><p className="mt-5 text-lg">“Born out of a love for India's people and places, Tripsthan connects travelers directly with local experts. We believe in transparent pricing, empowering local communities, and journeys that stay with you long after you return.”</p></div></section>
<section className="mx-auto max-w-6xl px-5 py-16"><h2 className="mb-8 text-center text-3xl">Our Identity, Vision and Values</h2>
<div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{V.map(([a,b])=><div key={a} className="card p-5"><h3 className="text-base text-saffron">{a}</h3><p className="mt-1 text-sm">{b}</p></div>)}</div>
<div className="card mt-8 grid gap-6 p-8 md:grid-cols-2 md:divide-x md:divide-line"><div><h3>Vision</h3><p className="mt-2">To be the most trusted way to explore India, with private, flexible journeys for every traveler.</p></div><div className="md:pl-8"><h3>Mission</h3><p className="mt-2">To deliver memorable, safe and affordable trips through local expertise, honesty and care.</p></div></div></section>
<section className="bg-warm"><div className="mx-auto max-w-3xl px-5 py-16"><h2 className="mb-6 text-3xl">Most Frequently Asked Questions</h2>{F.map(([q,a])=><details key={q} className="card mb-3 p-4"><summary className="cursor-pointer font-semibold text-ink">{q}</summary><p className="mt-2 text-sm">{a}</p></details>)}</div></section></main>)}
