"use client";
import {useState} from "react";import Link from "next/link";import PackageCard from "./PackageCard";import {img} from "@/lib/images";import {packages,featured,wa} from "@/lib/data";
const Chip=({on,...p})=><button {...p} className={`shrink-0 rounded-full border px-5 py-2 text-sm font-medium transition ${on?"border-saffron bg-saffron text-white":"border-line bg-warm text-ink"}`}/>;
const Head=({t,s})=><div className="mb-8"><h2 className="text-3xl">{t}</h2>{s&&<p className="mt-1">{s}</p>}</div>;
export function Offers(){const T=["All Tours","Adventure","Wildlife","Cultural"];const [t,s]=useState(T[0]);
const list=t===T[0]?featured:packages.filter(p=>p.tag===t).slice(0,4);return(<>
<div className="border-b border-line bg-white"><div className="mx-auto flex max-w-6xl gap-3 overflow-x-auto px-5 py-5">{T.map(x=><Chip key={x} on={t===x} onClick={()=>s(x)}>{x}</Chip>)}</div></div>
<section className="bg-warm"><div className="mx-auto max-w-6xl px-5 py-16"><Head t="Our Special Offers" s="Let us plan a perfect India holiday for you."/>
{list.length?<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-4">{list.map((p,i)=><PackageCard key={t+p.slug} p={p} i={i}/>)}</div>:<p className="card p-6">No {t.toLowerCase()} packages yet. <a className="font-semibold text-saffron" href={wa}>Ask us for a custom plan.</a></p>}<div className="mt-10 text-center"><Link href="/tours" className="btn px-8 text-lg shadow-card">View All Packages ({packages.length}+)</Link></div></div></section></>)}
export function Destinations(){const R=["Rajasthan","Himachal","Uttar Pradesh","Delhi","Uttarakhand"];const [r,s]=useState(R[0]);return(
<section className="mx-auto max-w-6xl px-5 py-16"><div className="flex items-end justify-between"><Head t="Popular Destinations" s="Himachal Holiday Packages, Rajasthan circuits and spiritual Ganges trips by private AC car."/><Link href="/tours" className="mb-8 text-sm font-semibold text-saffron">View all destinations</Link></div>
<div className="-mt-2 mb-8 flex gap-3 overflow-x-auto">{R.map(x=><Chip key={x} on={r===x} onClick={()=>s(x)}>{x}</Chip>)}</div>
<div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{packages.filter(p=>p.reg===r).map((p,i)=><PackageCard key={p.slug} p={p} i={i%3}/>)}</div></section>)}
const W=[["Expert Local Guides","Our certified guides know every hidden gem. Experience India like a local, not a tourist."],["100% Customizable Tours","Build your perfect trip from scratch. Choose duration, budget, activities, and more."],["Best Price Guarantee","We match and beat competitor pricing. Premium experiences at the most reasonable costs."],["24/7 Travel Support","Round-the-clock assistance throughout your journey. We're always just a call away."]];
export function Why(){return(<section className="bg-warm"><div className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-16 lg:grid-cols-2">
<div className="relative h-72 overflow-hidden rounded-card bg-dark bg-cover bg-center shadow-card lg:h-[28rem]" style={{backgroundImage:"url("+img("peaks",1400)+")"}}><div className="absolute inset-x-4 bottom-4 flex items-center justify-between rounded-card bg-white p-4 shadow-card"><div><b className="text-ink">5,000+ travelers</b><p className="text-xs">trust Tripsthan every year</p></div><div className="text-right"><b className="text-2xl text-saffron">4.9</b><p className="text-xs">avg rating</p></div></div></div>
<div><h2 className="text-3xl">Why Choose Tripsthan for Your Next Adventure</h2><ul className="mt-8 space-y-5">{W.map(([a,b],i)=><li key={a} className="flex gap-4"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-saffron text-sm font-bold text-white">{i+1}</span><div><h3 className="text-base">{a}</h3><p className="text-sm">{b}</p></div></li>)}</ul><Link href="/contact" className="btn mt-8">Start Planning</Link></div></div></section>)}
export function Services(){return(<section className="mx-auto max-w-6xl px-5 py-16"><Head t="What We Do For You"/><div className="grid gap-6 md:grid-cols-2">
{[["Private & Customized Tours","Build an unforgettable experience with help of multiple local expert agents. Add offbeat attractions, choose local cuisines, and add local activities. Best priced packages for your holiday duration."],["Car Rental Services","We provide luxury cars for tourists. Every moment from the time you arrive until the time you return, we ensure your comfort and safety throughout your journey."]].map(([a,b])=><div key={a} className="card p-8"><h3 className="text-xl">{a}</h3><p className="mt-3">{b}</p><a href={wa} className="btn mt-6 !py-2 text-sm">Enquire Now</a></div>)}</div></section>)}
const Q=[["Priya Sharma","Mumbai","The Rajasthan tour was beyond amazing. Every detail was perfectly planned and our guide was incredibly knowledgeable. Highly recommend Tripsthan!"],["Arjun Mehta","Bangalore","Wildlife safari at Ranthambore was the highlight of my year. Spotted two tigers! The team at Tripsthan is genuinely passionate about travel."],["Sarah Johnson","London","As a solo international traveler, I felt completely safe and well looked after. The Golden Triangle package was expertly curated. Will be back!"]];
export function Testimonials(){return(<section className="bg-warm"><div className="mx-auto max-w-6xl px-5 py-16"><div className="mb-8 text-center"><h2 className="text-3xl">Stories from Our Travelers</h2><p>Real experiences from people who trusted us with their journey.</p></div>
<div className="grid gap-6 md:grid-cols-3">{Q.map(([n,c,t])=><figure key={n} className="card flex flex-col p-6"><p className="text-saffron">★★★★★</p><blockquote className="mt-3 flex-1 text-sm">“{t}”</blockquote><figcaption className="mt-4 border-t border-line pt-4 text-sm"><b className="text-ink">{n}</b><br/>{c}</figcaption></figure>)}</div></div></section>)}
