export const FLEET_CATEGORIES = [
  { id: "all", name: "All Fleet" },
  { id: "sedan", name: "Sedans" },
  { id: "suv", name: "Luxury SUVs" },
  { id: "tempo", name: "Tempo & Vans" },
];

export const FLEET = [
  {
    id: "swift-dzire",
    category: "sedan",
    categoryName: "Economy Sedan",
    name: "Maruti Suzuki Swift Dzire",
    tagline: "India's Most Reliable & Fuel-Efficient AC Sedan",
    image: "/cars/swift-dzire.jpg",
    passengers: "3-4 Passengers",
    luggage: "2-3 Luggage Bags",
    overview:
      "We are known for offering well-maintained Swift Dzire cars along with highly experienced drivers. Every booking includes Driver, Taxes, Fuel, and Doorstep Pickup/Drop.",
    highlights: [
      "Commercial Verified Chauffeur",
      "All State Taxes & Tolls Paid",
      "Fuel Charges Included",
      "Doorstep Pickup & Drop",
      "Chilled Air Conditioning",
      "Bluetooth & Music System",
    ],
    idealFor: "Couples, small families, business airport transfers, and same-day city excursions.",
  },
  {
    id: "toyota-etios",
    category: "sedan",
    categoryName: "Economy Sedan",
    name: "Toyota Etios",
    tagline: "Spacious Comfort & Legendary Toyota Reliability",
    image: "/cars/toyota-etios.jpg",
    passengers: "3-4 Passengers",
    luggage: "3-4 Luggage Bags",
    overview:
      "Known for spacious interiors, generous rear legroom, and an immense 592L boot. Ideal for outstation Golden Triangle road trips and family travel.",
    highlights: [
      "Massive 592L Boot Space",
      "Commercial Uniformed Driver",
      "Tolls, Taxes & Fuel Included",
      "Spacious Rear Legroom",
      "Smooth Highway Suspension",
      "Clean Sanitized Interiors",
    ],
    idealFor: "Outstation Golden Triangle road trips, Agra–Delhi transfers, and family luggage.",
  },
  {
    id: "innova-crysta",
    category: "suv",
    categoryName: "Luxury MPV / SUV",
    name: "Toyota Innova Crysta",
    tagline: "The Undisputed King of Indian Highway & Hill Travel",
    image: "/cars/innova-crysta.jpg",
    passengers: "6-7 Passengers",
    luggage: "4-5 Luggage Bags",
    overview:
      "Premium Toyota Innova Crysta with plush captain seats, multi-zone AC, and superior highway suspension. The most trusted luxury MPV for family vacations and Rajasthan circuits.",
    highlights: [
      "Plush Captain Middle-Row Seats",
      "Rear Dedicated AC Vents",
      "Unmatched Highway Balance & Safety",
      "Generous Luggage Capacity",
      "Experienced Hill & Highway Driver",
      "All Road Taxes & Parking Covered",
    ],
    idealFor: "Family holidays, Himachal hill drives, Golden Triangle, and long-distance circuits.",
  },
  {
    id: "force-urbania",
    category: "tempo",
    categoryName: "Luxury Tourist Van",
    name: "Force Urbania",
    tagline: "Next-Gen European Luxury Tourist Van with Reclining Seats",
    image: "/cars/force-urbania.jpg",
    passengers: "10, 13 & 17 Seats",
    luggage: "10-15 Luggage Bags",
    overview:
      "A premium, next-generation van featuring independent front suspension, modern aerodynamics, and luxury interiors. It targets the high-end tourist segment, VIP airport transfers, and luxury palace tours.",
    highlights: [
      "Seating Capacities: 10, 13, and 17 seats",
      "Independent Front Coil Suspension",
      "European Monocoque Design",
      "Individual AC Vents & USB Ports",
      "Ergonomic Reclining Seats",
      "Spacious Walk-Through Aisle",
    ],
    idealFor: "High-end tourist groups, international delegations, corporate retreats, and luxury palace tours.",
  },
];
