export const FLEET_CATEGORIES = [
  { id: "all", name: "All Fleet" },
  { id: "economy", name: "Economy Sedans" },
  { id: "suv", name: "Luxury SUVs & MPVs" },
  { id: "tempo", name: "Tempo Travellers & Vans" },
];

export const FLEET = [
  {
    id: "swift-dzire",
    category: "economy",
    categoryName: "Economy Sedan",
    name: "Maruti Suzuki Swift Dzire",
    tagline: "India's Most Reliable & Fuel-Efficient AC Sedan",
    image: "/cars/swift-dzire.jpg",
    passengers: "3-4 Passengers",
    luggage: "1-4 Luggage Bags",
    overview:
      "We are known for offering well-maintained Swift Dzire cars along with highly experienced drivers with include Driver, Taxes, Fuel, Pickup/Drop.",
    highlights: [
      "Driver Included",
      "All State Taxes & Tolls Paid",
      "Fuel Charges Included",
      "Doorstep Pickup & Drop",
      "Chilled Air Conditioning",
      "Bluetooth & Music System",
    ],
    idealFor: "Couples, small families, business airport transfers, and same-day city excursions.",
  },
  {
    id: "toyota-etios",
    category: "economy",
    categoryName: "Economy Sedan",
    name: "Toyota Etios",
    tagline: "Spacious Comfort & Legendary Toyota Reliability",
    image: "/cars/toyota-etios.jpg",
    passengers: "3-4 Passengers",
    luggage: "1-4 Luggage Bags",
    overview:
      "We are known for offering well-maintained sedan Etios cars along with highly experienced drivers with include Driver, Taxes, Fuel, Pickup/Drop.",
    highlights: [
      "Massive 592L Boot Space",
      "Commercial Uniformed Driver",
      "Tolls, Taxes & Fuel Included",
      "Spacious Rear Legroom",
      "Smooth Highway Suspension",
      "Clean Sanitized Interiors",
    ],
    idealFor: "Outstation Golden Triangle road trips, Agra–Delhi transfers, and family luggage.",
  },
  {
    id: "innova-hycross",
    category: "suv",
    categoryName: "Luxury MPV / SUV",
    name: "Toyota Innova Hycross",
    tagline: "The Future of Luxury Touring with Ottoman Lounge Seating",
    image: "/cars/innova-hycross.jpg",
    passengers: "6-7 Passengers",
    luggage: "4-5 Luggage Bags",
    overview:
      "We are known for offering well-maintained SUV Sedan cars along with highly experienced drivers with include Driver, Taxes, Fuel, Pickup/Drop.",
    highlights: [
      "Ottoman Captain Recliner Seats",
      "Whisper-Quiet Hybrid Cabin",
      "Panoramic Sunroof & Ambient Light",
      "Multi-Zone Climate AC",
      "Fuel, Taxes & Driver Included",
      "VIP Hospitality Chauffeuring",
    ],
    idealFor: "VIP luxury tours, executive delegations, weddings, and premium Rajasthan journeys.",
  },
  {
    id: "innova-crysta",
    category: "suv",
    categoryName: "Luxury MPV / SUV",
    name: "Toyota Innova Crysta",
    tagline: "The Undisputed King of Indian Highway Travel",
    image: "/cars/innova-crysta.jpg",
    passengers: "6-7 Passengers",
    luggage: "4-5 Luggage Bags",
    overview:
      "We are known for offering well-maintained Toyota Innova Crysta cars along with highly experienced drivers with include Driver, Taxes, Fuel, Pickup/Drop.",
    highlights: [
      "Plush Captain Middle-Row Seats",
      "Rear Dedicated AC Vents",
      "Unmatched Highway Balance & Safety",
      "Generous Luggage Capacity",
      "Experienced Hill & Highway Driver",
      "All Road Taxes & Parking Covered",
    ],
    idealFor: "Family holidays, Himachal hill drives, Golden Triangle, and long-distance circuits.",
  },
  {
    id: "kia-carens",
    category: "suv",
    categoryName: "Luxury MPV / SUV",
    name: "Kia Carens",
    tagline: "Modern 3-Row Tech-Luxe Touring Experience",
    image: "/cars/kia-carens.jpg",
    passengers: "6-7 Passengers",
    luggage: "3-4 Luggage Bags",
    overview:
      "We are known for offering well-maintained modern luxury cars along with highly experienced drivers with include Driver, Taxes, Fuel, Pickup/Drop.",
    highlights: [
      "One-Touch Electric Tumble Seats",
      "Sky-Light Sunroof",
      "Air Purifier & Bose Audio",
      "Rear Sunshade Curtains",
      "Professional Chauffeur",
      "Complete Fuel & Tax Inclusions",
    ],
    idealFor: "Modern family tours, weekend retreats, airport transfers, and corporate hire.",
  },
  {
    id: "force-urbania",
    category: "tempo",
    categoryName: "Luxury Tourist Van",
    name: "Force Urbania",
    tagline: "Next-Gen European Luxury Tourist Van with Independent Suspension",
    image: "/cars/force-urbania.jpg",
    passengers: "10, 13 & 17 Seats",
    luggage: "10-15 Luggage Bags",
    overview:
      "A premium, next-generation van featuring independent front suspension, modern aerodynamics, and luxury interiors. It targets the high-end tourist segment, VIP airport transfers, and luxury hotel fleets.",
    highlights: [
      "Seating Capacities: 10, 13, and 17 seats",
      "Independent Front Coil Suspension",
      "European Monocoque Design",
      "Individual AC Vents & USB Ports",
      "Ergonomic Reclining Seats",
      "Spacious Walk-Through Aisle",
    ],
    idealFor: "High-end tourist groups, international delegations, corporate retreats, and luxury palace tours.",
  },
  {
    id: "force-traveller",
    category: "tempo",
    categoryName: "Luxury Tempo Traveller",
    name: "Force Traveller",
    tagline: "India's #1 Trusted Group Tour Minibus for Every Circuit",
    image: "/cars/force-traveller.jpg",
    passengers: "9 to 26 Seats Available",
    luggage: "Rooftop Carrier + Rear Boot",
    overview:
      "Seating Capacities range from 9 up to 26 seats, depending on the body configuration. Available in 3050 mm, 3350 mm, 3700 mm, 4020 mm, and 5200 mm wheelbases.",
    highlights: [
      "Wheelbases: 3050mm to 5200mm",
      "Pushback 2x1 Reclining Seats",
      "High-Roof Standing Cabin",
      "Roof Carrier for Heavy Baggage",
      "Uniformed Verified Highway Driver",
      "All State Border Permits Covered",
    ],
    idealFor: "Pilgrimage groups, student excursions, wedding guests, and multi-city grand tours.",
  },
  {
    id: "force-trax-cruiser",
    category: "tempo",
    categoryName: "Rugged Heavy-Duty MUV",
    name: "Force Trax Cruiser",
    tagline: "High-Capacity Heavy-Duty MUV for Rural, Semi-Urban & Mountain Terrain",
    image: "/cars/force-trax-cruiser.jpg",
    passengers: "10 to 13 Seats",
    luggage: "Rooftop Luggage Carrier",
    overview:
      "While technically a rugged MUV rather than a traditional van, the Trax Cruiser is heavily utilized as a high-capacity people mover for shared commercial transport in rural, semi-urban, and hilly regions.",
    highlights: [
      "High-Capacity Seating: 10 to 13 seats",
      "High Ground Clearance & Rugged Chassis",
      "Built for Harsh Hill & Rural Terrains",
      "Heavy-Duty Roof Baggage Rack",
      "Experienced Rough-Road Driver",
      "Fuel, Taxes & Chauffeur Included",
    ],
    idealFor: "Hilly roads, rural expeditions, rugged wilderness, and budget high-capacity travel.",
  },
];
