import {img} from "./images";
export const C={phones:["+91 7982625081","+91 9953458949"],emails:["Sonucarrentals@gmail.com","Tripsthan@gmail.com"],address:"Agra, Uttar Pradesh, India"};
export const tel=p=>"tel:"+p.replace(/\s/g,"");
export const wa="https://wa.me/917982625081";
const base="Private air-conditioned car with an experienced driver";
const J="Amber Palace, Hawa Mahal, Jal Mahal, Jantar Mantar and City Palace, plus the old-city markets";
const DEL="India Gate, Rashtrapati Bhavan, Humayun's Tomb and Qutub Minar";
const TAJ="the Taj Mahal and Agra Fort";
const mk=(slug,title,days,price,tag,reg,overview,highlights,itinerary)=>({slug,title,days,price,tag,reg,overview,highlights:[...highlights,base],itinerary});
export const more=[
mk("jaipur-day-tour","Jaipur Day Tour – Full-Day Sightseeing",1,"On request","Cultural","Rajasthan","A complete Pink City tour of palaces, forts and bazaars in one day.",["Amber Palace hilltop views","Hawa Mahal and Jal Mahal photo stop","Jantar Mantar and City Palace","Pink City walking or rickshaw experience"],
[["Morning: Forts & Palaces","Pickup from your Jaipur hotel. Visit Amber Palace, Hawa Mahal, a Jal Mahal photo stop, Jantar Mantar and the City Palace."],["Afternoon: Pink City","Explore the old city's markets for textiles, jewelry and handicrafts on foot or by rickshaw. Drop-off at your hotel."]]),
mk("7-day-golden-triangle-varanasi","7 Days Golden Triangle Tour with Varanasi",7,"On request","Pilgrimage","Uttar Pradesh","Delhi, Jaipur, Agra, Lucknow and Varanasi: royal heritage plus the spirituality of the Ganges.",["Complete Jaipur, Agra, Lucknow, Varanasi circuit","Taj Mahal and Agra Fort","Bara Imambara and Rumi Darwaza, Lucknow","Evening Ganga Aarti and optional sunrise boat ride"],
[["Delhi to Jaipur","Private drive to Jaipur; check in and relax. Overnight: Jaipur."],["Jaipur Sightseeing",J+". Overnight: Jaipur."],["Jaipur to Agra","Drive to Agra and visit "+TAJ+". Overnight: Agra."],["Agra to Lucknow","Drive to the city of Nawabs; see Bara Imambara, Chota Imambara and Rumi Darwaza. Overnight: Lucknow."],["Lucknow to Varanasi","Transfer to Varanasi and watch the Ganga Aarti on the ghats. Overnight: Varanasi."],["Varanasi Sightseeing","Optional sunrise boat ride, then ancient temples and narrow lanes. Overnight: Varanasi."],["Departure","Transfer to the airport or railway station after breakfast."]]),
mk("12-day-himachal-amritsar","12 Days Himachal & Amritsar Tour – Shimla, Manali, Dharamshala & Golden Temple",12,"On request","Adventure","Himachal","Mountains and spirituality across Shimla, Manali, Dharamshala, Amritsar and Chandigarh.",["Shimla Mall Road, Ridge, Christ Church, Jakhoo Temple","Old Manali, Hadimba Temple, optional Solang Valley or Rohtang Pass","Tsuglagkhang Complex and McLeod Ganj","Golden Temple, Jallianwala Bagh, Wagah Border ceremony"],
[["Arrival in Delhi","Arrive, check in and rest. Overnight: Delhi."],["Drive to Shimla","Drive to the former summer capital of British India. Overnight: Shimla."],["Shimla Sightseeing","Mall Road, Ridge, Christ Church and Jakhoo Temple. Overnight: Shimla."],["Drive to Manali","Scenic valley and riverside drive. Overnight: Manali."],["Manali Sightseeing","Hadimba Temple, Old Manali and Mall Road. Overnight: Manali."],["Manali Leisure / Excursions","Optional Solang Valley or Rohtang Pass, subject to weather and road conditions. Overnight: Manali."],["Drive to Dharamshala","Home to a large Tibetan community and the Dalai Lama's residence. Overnight: Dharamshala."],["Dharamshala Sightseeing","Tsuglagkhang Complex, Namgyal Monastery and the Tibet Museum in McLeod Ganj. Overnight: Dharamshala."],["Drive to Amritsar","Check in, then the Wagah Border ceremony in the evening. Overnight: Amritsar."],["Amritsar Sightseeing","Golden Temple, Jallianwala Bagh and the old-city markets. Overnight: Amritsar."],["Drive to Chandigarh","Evening at leisure in India's planned city. Overnight: Chandigarh."],["Drive Back to Delhi","Drop-off at your hotel, the airport or another location."]]),
mk("10-day-rajasthan-tour","10 Days Rajasthan Tour – Royal Palaces, Forts & Desert Experience",10,"On request","Cultural","Rajasthan","Agra, Jaipur, Bikaner, Jaisalmer, Jodhpur and Udaipur, upgradeable to heritage havelis and palace hotels.",["Taj Mahal and Agra Fort","Junagarh Fort, Bikaner","Jaisalmer Fort and optional camel safari","Mehrangarh Fort, Jodhpur","City Palace and Lake Pichola, Udaipur"],
[["Delhi to Agra","Drive to Agra and check in. Overnight: Agra."],["Agra to Jaipur","Visit "+TAJ+", then drive to Jaipur. Overnight: Jaipur."],["Jaipur Sightseeing",J+". Overnight: Jaipur."],["Jaipur to Bikaner","Explore Junagarh Fort, havelis and local markets. Overnight: Bikaner."],["Bikaner to Jaisalmer","Drive to the Golden City. Overnight: Jaisalmer."],["Jaisalmer Sightseeing","Jaisalmer Fort, Patwon Ki Haveli and the dunes; optional camel safari or desert camp. Overnight: Jaisalmer."],["Jaisalmer to Jodhpur","Visit Mehrangarh Fort and the indigo old town. Overnight: Jodhpur."],["Jodhpur to Udaipur","Lakeside evening in the City of Lakes. Overnight: Udaipur."],["Udaipur Sightseeing","City Palace, Jagdish Temple, Saheliyon Ki Bari; optional Lake Pichola boat ride. Overnight: Udaipur."],["Departure","Transfer to Udaipur Airport for your onward flight to Mumbai, Goa or elsewhere."]]),
mk("7-day-golden-triangle-pushkar","7 Days Golden Triangle Tour with Pushkar",7,"On request","Pilgrimage","Rajasthan","Delhi, Agra and Jaipur, ending at Pushkar's sacred lake.",["Fatehpur Sikri","Taj Mahal and Agra Fort","Pushkar Lake and Brahma Temple","Pushkar bazaars"],
[["Delhi Sightseeing",DEL+" and Jama Masjid, depending on time. Overnight: Delhi."],["Delhi to Agra","Drive to Agra; visit Agra Fort and the Taj Mahal. Overnight: Agra."],["Agra to Jaipur via Fatehpur Sikri","Stop at the abandoned Mughal capital en route. Overnight: Jaipur."],["Jaipur Sightseeing",J+". Overnight: Jaipur."],["Jaipur to Pushkar","Drive to the sacred lake town. Overnight: Pushkar."],["Pushkar Sightseeing","Pushkar Lake ghats, Brahma Temple and colorful bazaars. Overnight: Pushkar."],["Drive Back to Delhi","Drop-off at your hotel, the airport or another location."]]),
mk("same-day-taj-mahal-tour","Same Day Taj Mahal Tour from Delhi",1,"₹8,500","Cultural","Uttar Pradesh","A private Delhi–Agra round trip in a single day, with no overnight stay.",["Guided Taj Mahal visit","Agra Fort with Taj views","Lunch and shopping time"],
[["Early Pickup & Drive to Agra","Pickup from your Delhi hotel or airport, then a 3–4 hour drive to Agra."],["Taj Mahal & Agra Fort","Guided Taj Mahal visit, then Agra Fort for its views and history."],["Lunch, Shopping & Return","Lunch at a local restaurant and free time in Agra's markets, then drive back to Delhi."]]),
mk("7-day-golden-triangle-rishikesh","7 Days Golden Triangle & Rishikesh Tour – Spiritual India Experience",7,"On request","Pilgrimage","Uttarakhand","Jaipur, Agra and Delhi, then Rishikesh, the yoga capital on the Ganges.",["Taj Mahal and Agra Fort","Old Delhi: Jama Masjid, Chandni Chowk, Red Fort","Laxman Jhula and Ram Jhula","Optional yoga, meditation, rafting and Ganga Aarti"],
[["Delhi to Jaipur","Private drive to the Pink City. Overnight: Jaipur."],["Jaipur Sightseeing",J+". Overnight: Jaipur."],["Jaipur to Agra","Visit "+TAJ+". Overnight: Agra."],["Delhi & Half-Day Delhi Tour","Drive to Delhi, then "+DEL+". Overnight: Delhi."],["Old Delhi & Drive to Rishikesh","Jama Masjid, Chandni Chowk and Red Fort, then drive to Rishikesh. Overnight: Rishikesh."],["Rishikesh","Laxman Jhula, Ram Jhula, riverside ashrams; optional yoga, meditation, rafting and Ganga Aarti. Overnight: Rishikesh."],["Drive to Delhi","Drop-off at your hotel, the airport or another location."]]),
mk("4-day-haridwar-rishikesh","4 Days Holy River Ganga Tour – Haridwar & Rishikesh",4,"On request","Pilgrimage","Uttarakhand","A short spiritual escape along the Ganges, also suited to yoga and wellness.",["Delhi sightseeing","Haridwar ghats","Laxman Jhula, Ram Jhula and ashrams","Optional yoga, rafting and Ganga Aarti"],
[["Delhi Sightseeing",DEL+" and Jama Masjid, depending on time. Overnight: Delhi."],["Drive to Rishikesh via Haridwar","Explore Haridwar's ghats, then continue to Rishikesh. Overnight: Rishikesh."],["Rishikesh","Laxman Jhula, Ram Jhula and ashrams; optional yoga, meditation, rafting and Ganga Aarti. Overnight: Rishikesh."],["Drive to Delhi","Drop-off at your hotel, the airport or another location."]]),
mk("7-day-shimla-manali","7 Days Shimla Manali Tour – Himachal Hill Station Getaway",7,"On request","Adventure","Himachal","Colonial Shimla, adventurous Manali and a stop in Chandigarh.",["Shimla Mall Road, Ridge, Christ Church, Jakhoo Temple","Hadimba Temple and Old Manali","Optional Solang Valley or Rohtang Pass","Chandigarh stopover"],
[["Delhi to Shimla","Drive to Shimla and enjoy the evening. Overnight: Shimla."],["Shimla Sightseeing","Mall Road, Ridge, Christ Church and Jakhoo Temple. Overnight: Shimla."],["Drive to Manali","Scenic valleys and riverside roads. Overnight: Manali."],["Manali Sightseeing","Hadimba Temple, Old Manali and Mall Road. Overnight: Manali."],["Manali Leisure / Excursions","Optional Solang Valley or Rohtang Pass, subject to weather. Overnight: Manali."],["Drive to Chandigarh","Evening exploring the city. Overnight: Chandigarh."],["Drive Back to Delhi","Drop-off at your hotel, the airport or another location."]])
];

const raw=[...[
{reg:"Uttar Pradesh",slug:"2-day-taj-mahal-delhi",title:"2-Day Taj Mahal & Delhi Tour",days:2,price:"₹8,500",tag:"Cultural",
overview:"A quick yet complete introduction to Delhi and Agra, with a sunrise visit to the Taj Mahal.",
highlights:["Full day of Delhi sightseeing","Sunrise Taj Mahal visit","Guided Agra Fort",base,"Flexible pickup and drop-off"],
itinerary:[["Delhi Sightseeing & Drive to Agra","Explore Rashtrapati Bhavan, India Gate and Qutub Minar, then drive 3–4 hours to Agra by private AC car. Overnight: Agra."],["Agra Sightseeing & Drive Back to Delhi","Early-morning Taj Mahal with a local guide, then Agra Fort, lunch and shopping before the drive back. Drop-off at your chosen location."]]},
{reg:"Rajasthan",slug:"5-day-golden-triangle",title:"5-Day Golden Triangle Tour – Delhi, Agra & Jaipur",days:5,price:"On request",tag:"Cultural",
overview:"Mughal heritage and royal Rajasthani culture at a comfortable private pace.",
highlights:["Agra Fort and Taj Mahal","Fatehpur Sikri and Chand Baori stepwell","Amber Palace, City Palace, Jantar Mantar","Pink City walk or rickshaw ride",base],
itinerary:[["Arrival & Delhi Sightseeing","Visit Rashtrapati Bhavan, India Gate, Humayun's Tomb, Qutub Minar, Jama Masjid and Raj Ghat. Overnight: Delhi."],["Delhi to Agra","Drive to Agra; visit Agra Fort and the Taj Mahal. Overnight: Agra."],["Agra – Fatehpur Sikri – Abhaneri – Jaipur","Optional Taj sunrise, then Fatehpur Sikri and the Chand Baori stepwell before reaching Jaipur. Overnight: Jaipur."],["Jaipur Sightseeing","Amber Palace, Hawa Mahal, Jal Mahal photo stop, Jantar Mantar, City Palace and the Pink City streets."],["Jaipur to Delhi","Private drive back to Delhi; tour concludes at your hotel or airport."]]},
{reg:"Rajasthan",slug:"7-day-golden-triangle-jungle",title:"7 Days Golden Triangle with Jungle Tour",days:7,price:"₹18,500",tag:"Wildlife",
overview:"Iconic monuments plus a full-day tiger safari in Ranthambore.",
highlights:["Taj Mahal and Agra Fort","Bharatpur Bird Sanctuary","Full-day Ranthambore safari","Amber Palace and Pink City",base],
itinerary:[["Half-Day Delhi Tour & Drive to Agra","India Gate, Rashtrapati Bhavan, Humayun's Tomb, Qutub Minar, then drive to Agra."],["Agra Sightseeing","Taj Mahal and Agra Fort."],["Agra to Ranthambore via Bharatpur","Stop at Keoladeo National Park, a UNESCO site, then continue to Ranthambore."],["Ranthambore Safari","Jeep or canter safari in search of tigers, leopards, deer and birds."],["Drive to Jaipur","Check in and relax in the Pink City."],["Jaipur Sightseeing","Amber Palace, Hawa Mahal, Jal Mahal, Jantar Mantar, City Palace and old-city bazaars."],["Drive to Delhi","Drop-off at your hotel or the airport."]]},
{reg:"Delhi",slug:"old-new-delhi-day-tour",title:"Old & New Delhi Day Tour",days:1,price:"On request",tag:"Cultural",
overview:"Mughal-era Old Delhi and colonial-era New Delhi in one guided day.",
highlights:["Jama Masjid, Red Fort, Chandni Chowk","India Gate, Humayun's Tomb, Qutub Minar","Optional rickshaw ride",base],
itinerary:[["Morning: Old Delhi","Jama Masjid, Red Fort, Chandni Chowk and Raj Ghat, with an optional rickshaw ride."],["Afternoon: New Delhi","India Gate, Rashtrapati Bhavan, Humayun's Tomb, Qutub Minar and, time permitting, Lotus Temple."]]}

],...more];

const IM={"2-day-taj-mahal-delhi":"taj","5-day-golden-triangle":"hawa","7-day-golden-triangle-jungle":"tiger","old-new-delhi-day-tour":"gate","jaipur-day-tour":"amber","7-day-golden-triangle-varanasi":"varanasi","12-day-himachal-amritsar":"manali","10-day-rajasthan-tour":"amber","7-day-golden-triangle-pushkar":"hawa","same-day-taj-mahal-tour":"taj2","7-day-golden-triangle-rishikesh":"peaks","4-day-haridwar-rishikesh":"varanasi","7-day-shimla-manali":"manali"};
const OV={
"2-day-taj-mahal-delhi":"A relaxed escape pairing Delhi's landmarks with a sunrise Taj Mahal visit. Travel by private AC car with an English-speaking local guide and a comfortable overnight stay in Agra.",
"5-day-golden-triangle":"Our signature Golden Triangle Tour India: Delhi, Agra and Jaipur in five unhurried days. Includes a Private Delhi Agra Jaipur Cab, heritage walks, Fatehpur Sikri, Chand Baori stepwell and optional luxury stays.",
"7-day-golden-triangle-jungle":"Pair India's great monuments with a thrilling tiger safari in Ranthambore and a birdwatching stop at Bharatpur. A Golden Triangle Tour India for travelers who want heritage and wildlife in one private trip.",
"12-day-himachal-amritsar":"Our most complete Himachal Holiday Package: colonial Shimla, snowy Manali, Tibetan Dharamshala and the glowing Golden Temple of Amritsar, with a private car and driver throughout.",
"old-new-delhi-day-tour":"Walk Mughal lanes in Old Delhi and wide colonial boulevards in New Delhi in one guided day, with a private AC car and English-speaking guide.",
"jaipur-day-tour":"See Amber Palace, Hawa Mahal, Jantar Mantar and the City Palace in a single day of Pink City heritage, with a private AC car and local guide.",
"7-day-golden-triangle-varanasi":"A Golden Triangle Tour India that continues to Lucknow's Nawabi heritage and the sacred ghats of Varanasi, including the evening Ganga Aarti.",
"10-day-rajasthan-tour":"Forts, palaces and desert dunes from Agra to Udaipur, with the option to upgrade to heritage havelis and luxury palace stays.",
"7-day-golden-triangle-pushkar":"Delhi, Agra and Jaipur by Private Delhi Agra Jaipur Cab, then a peaceful finale at Pushkar's sacred lake.",
"same-day-taj-mahal-tour":"A Same Day Taj Mahal Tour by Car from Delhi: private AC transport, a guided Taj Mahal and Agra Fort visit, lunch and a return the same evening.",
"7-day-golden-triangle-rishikesh":"Golden Triangle Tour India with a spiritual finish in Rishikesh: yoga, riverside ashrams, rafting and the evening Ganga Aarti.",
"4-day-haridwar-rishikesh":"A short Ganges escape through Haridwar's ghats and Rishikesh's yoga ashrams, ideal for wellness and meditation.",
"7-day-shimla-manali":"A relaxed Himachal Holiday Package through pine forests and snow-capped peaks, from Shimla's Mall Road to Manali's valleys."};
const IT={
"2-day-taj-mahal-delhi":[["Delhi Heritage Drive & Journey to Agra","After a smooth pickup, drive past Rashtrapati Bhavan and India Gate, then climb the carved sandstone of Qutub Minar with your English-speaking guide. Settle into the private AC car for the 3–4 hour drive to Agra and check in. Overnight: Agra."],["Sunrise at the Taj Mahal & Agra Fort","Reach the Taj Mahal at first light, when the white marble glows soft pink and the crowds are thin. Your guide shares the story behind the inlay work and gardens. Continue to Agra Fort for views of the Taj, then enjoy lunch and a little shopping before the drive back to Delhi."]],
"5-day-golden-triangle":[["Arrival & Delhi Heritage Sightseeing","Meet your driver and guide, then trace Delhi's layered history: Humayun's Tomb, India Gate, Rashtrapati Bhavan, Qutub Minar, Jama Masjid and Raj Ghat. Add a rickshaw ride through Old Delhi's lanes or the Lotus Temple if time allows. Overnight: Delhi."],["Delhi to Agra – The City of the Taj","Drive in your private AC car to Agra. Explore the red sandstone ramparts of Agra Fort, then stand before the Taj Mahal, with its marble domes, inlay work and gardens. Overnight: Agra."],["Taj Sunrise, Fatehpur Sikri, Abhaneri & Jaipur","Optionally return to the Taj at sunrise for a softer, quieter view. En route to Jaipur, wander the abandoned Mughal capital of Fatehpur Sikri and photograph the Chand Baori stepwell at Abhaneri. Overnight: Jaipur."],["Jaipur – The Pink City","Ride up to Amber Palace, photograph Hawa Mahal and the floating Jal Mahal, then visit Jantar Mantar and the City Palace. Finish with a heritage walk or rickshaw ride through the rose-pink bazaars. Overnight: Jaipur."],["Jaipur to Delhi – Tour Concludes","After a leisurely breakfast, enjoy the private drive back to Delhi, with drop-off at your hotel, the airport or another chosen location."]]};
export const packages=raw.map(p=>({...p,overview:OV[p.slug]||p.overview,itinerary:IT[p.slug]||p.itinerary,img:img(IM[p.slug]||"taj",900),hero:img(IM[p.slug]||"taj",1800)}));
export const featured=["2-day-taj-mahal-delhi","5-day-golden-triangle","7-day-golden-triangle-jungle","12-day-himachal-amritsar"].map(s=>packages.find(p=>p.slug===s));
