// Auto-generated gallery dataset with all 61 photos from desktop tripsthan images folder
export const GALLERY_CATEGORIES = [
  "All",
  "Heritage & Palaces",
  "Guest Experiences",
  "Luxury Fleet & Cabs",
  "Culture & Sightseeing",
  "Tours & Highlights"
];

export const GALLERY_ITEMS = [
  {
    "id": 1,
    "src": "/gallery/tripsthan-img-01.jpg",
    "fileName": "tripsthan-img-01.jpg",
    "originalName": "_DSC3890S1.JPG.jpeg",
    "title": "Majestic Fort Architecture & Royal Courtyard",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 3542,
    "height": 4117,
    "aspectRatio": 0.86,
    "isFeatured": true
  },
  {
    "id": 2,
    "src": "/gallery/tripsthan-img-02.jpg",
    "fileName": "tripsthan-img-02.jpg",
    "originalName": "_DSC4463S.JPG.jpeg",
    "title": "Heritage Archways & Intricate Mughal Carvings",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 4896,
    "height": 3532,
    "aspectRatio": 1.39,
    "isFeatured": true
  },
  {
    "id": 3,
    "src": "/gallery/tripsthan-img-03.jpg",
    "fileName": "tripsthan-img-03.jpg",
    "originalName": "20181120_110314S.jpg.jpeg",
    "title": "Golden Triangle Historic Monument Tour",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1944,
    "height": 2592,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 4,
    "src": "/gallery/tripsthan-img-04.jpg",
    "fileName": "tripsthan-img-04.jpg",
    "originalName": "20260216_102508.jpg.jpeg",
    "title": "Chauffeur Driven City Tour in Jaipur",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 3056,
    "height": 3056,
    "aspectRatio": 1,
    "isFeatured": false
  },
  {
    "id": 5,
    "src": "/gallery/tripsthan-img-05.jpg",
    "fileName": "tripsthan-img-05.jpg",
    "originalName": "20260304_061222.jpg.jpeg",
    "title": "Morning Sunrise View at the Historic Citadel",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 4128,
    "height": 3096,
    "aspectRatio": 1.33,
    "isFeatured": true
  },
  {
    "id": 6,
    "src": "/gallery/tripsthan-img-06.jpg",
    "fileName": "tripsthan-img-06.jpg",
    "originalName": "20260304_092508.jpg.jpeg",
    "title": "Scenic Highway Drive Across Rajasthan",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1920,
    "height": 1920,
    "aspectRatio": 1,
    "isFeatured": false
  },
  {
    "id": 7,
    "src": "/gallery/tripsthan-img-07.jpg",
    "fileName": "tripsthan-img-07.jpg",
    "originalName": "20260304_092554.jpg.jpeg",
    "title": "Panoramic Hilltop Fort & Ramparts",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 4128,
    "height": 3096,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 8,
    "src": "/gallery/tripsthan-img-08.jpg",
    "fileName": "tripsthan-img-08.jpg",
    "originalName": "506453726_24290248683892254_1720264602312099321_n.jpg.jpeg",
    "title": "Private AC Cab Pickup for Delhi Agra Tour",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 480,
    "height": 360,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 9,
    "src": "/gallery/tripsthan-img-09.jpg",
    "fileName": "tripsthan-img-09.jpg",
    "originalName": "515442742_24453798700870584_6816106839762642874_n.jpg.jpeg",
    "title": "Happy International Guests on Agra Day Trip",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1440,
    "height": 1080,
    "aspectRatio": 1.33,
    "isFeatured": true
  },
  {
    "id": 10,
    "src": "/gallery/tripsthan-img-10.jpg",
    "fileName": "tripsthan-img-10.jpg",
    "originalName": "56985341_1979724845472579_8098222671252160512_n.jpg.jpeg",
    "title": "Traditional Rajasthani Architecture & Haveli",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 888,
    "height": 1600,
    "aspectRatio": 0.56,
    "isFeatured": false
  },
  {
    "id": 11,
    "src": "/gallery/tripsthan-img-11.jpg",
    "fileName": "tripsthan-img-11.jpg",
    "originalName": "60.jpg.jpeg",
    "title": "Luxury Sedan Chauffeur Service on Golden Route",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 720,
    "height": 480,
    "aspectRatio": 1.5,
    "isFeatured": false
  },
  {
    "id": 12,
    "src": "/gallery/tripsthan-img-12.jpg",
    "fileName": "tripsthan-img-12.jpg",
    "originalName": "7b.jpg.jpeg",
    "title": "Deluxe SUV Tour with English Speaking Driver",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 720,
    "height": 480,
    "aspectRatio": 1.5,
    "isFeatured": false
  },
  {
    "id": 13,
    "src": "/gallery/tripsthan-img-13.jpg",
    "fileName": "tripsthan-img-13.jpg",
    "originalName": "81003999_2479262582185467_6616035938508210176_n.jpg.jpeg",
    "title": "Exploring the Colorful Bazaars of Pink City",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 960,
    "height": 720,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 14,
    "src": "/gallery/tripsthan-img-14.jpg",
    "fileName": "tripsthan-img-14.jpg",
    "originalName": "81271966_2474894405955618_4961501140362461184_n.jpg.jpeg",
    "title": "Evening Palace Illumination & Heritage Walk",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1080,
    "height": 1440,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 15,
    "src": "/gallery/tripsthan-img-15.jpg",
    "fileName": "tripsthan-img-15.jpg",
    "originalName": "83145832_2517270878384637_2837691687105462272_n.jpg.jpeg",
    "title": "Memorable Guest Moments at Amber Palace",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1600,
    "height": 1200,
    "aspectRatio": 1.33,
    "isFeatured": true
  },
  {
    "id": 16,
    "src": "/gallery/tripsthan-img-16.jpg",
    "fileName": "tripsthan-img-16.jpg",
    "originalName": "84567464_2534743169970741_1997071844594679808_n.jpg.jpeg",
    "title": "Scenic Mountain & Valley Stopover",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1600,
    "height": 1200,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 17,
    "src": "/gallery/tripsthan-img-17.jpg",
    "fileName": "tripsthan-img-17.jpg",
    "originalName": "85128675_2545844435527281_4444602869965914112_n.jpg.jpeg",
    "title": "Ghats & Timeless Spiritual Heritage",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1200,
    "height": 1600,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 18,
    "src": "/gallery/tripsthan-img-18.jpg",
    "fileName": "tripsthan-img-18.jpg",
    "originalName": "88228492_2593991230712601_796775927294984192_n.jpg.jpeg",
    "title": "Royal Palace Gateway & Architectural Grandeur",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1536,
    "height": 2048,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 19,
    "src": "/gallery/tripsthan-img-19.jpg",
    "fileName": "tripsthan-img-19.jpg",
    "originalName": "89971239_2618365228275201_6049370975814811648_n.jpg.jpeg",
    "title": "Chauffeur Tour Across Historic Monuments",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1600,
    "height": 900,
    "aspectRatio": 1.78,
    "isFeatured": false
  },
  {
    "id": 20,
    "src": "/gallery/tripsthan-img-20.jpg",
    "fileName": "tripsthan-img-20.jpg",
    "originalName": "92435120_2664838646961192_8481798718624890880_n.jpg.jpeg",
    "title": "Relaxed Journey with Private AC Innova Crysta",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1080,
    "height": 1312,
    "aspectRatio": 0.82,
    "isFeatured": false
  },
  {
    "id": 21,
    "src": "/gallery/tripsthan-img-21.jpg",
    "fileName": "tripsthan-img-21.jpg",
    "originalName": "95047691_2713484208763302_3474331721569140736_n.jpg.jpeg",
    "title": "Scenic Desert Road & Camels in Rajasthan",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1080,
    "height": 810,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 22,
    "src": "/gallery/tripsthan-img-22.jpg",
    "fileName": "tripsthan-img-22.jpg",
    "originalName": "FB_IMG_1767241512752.jpg.jpeg",
    "title": "Guest Travelers Enjoying Authentic India Cuisine",
    "category": "Guest Experiences",
    "location": "Golden Triangle & Beyond",
    "width": 957,
    "height": 960,
    "aspectRatio": 1,
    "isFeatured": false
  },
  {
    "id": 23,
    "src": "/gallery/tripsthan-img-23.jpg",
    "fileName": "tripsthan-img-23.jpg",
    "originalName": "FB_IMG_1791279175702.jpg.jpeg",
    "title": "Jaipur City Palace Heritage Gates",
    "category": "Guest Experiences",
    "location": "Golden Triangle & Beyond",
    "width": 720,
    "height": 476,
    "aspectRatio": 1.51,
    "isFeatured": false
  },
  {
    "id": 24,
    "src": "/gallery/tripsthan-img-24.jpg",
    "fileName": "tripsthan-img-24.jpg",
    "originalName": "FB_IMG_1791279312147.jpg.jpeg",
    "title": "Agra Taj Mahal Day Tour Group Memory",
    "category": "Guest Experiences",
    "location": "Golden Triangle & Beyond",
    "width": 486,
    "height": 720,
    "aspectRatio": 0.68,
    "isFeatured": false
  },
  {
    "id": 25,
    "src": "/gallery/tripsthan-img-25.jpg",
    "fileName": "tripsthan-img-25.jpg",
    "originalName": "Image-32827.jpg.jpeg",
    "title": "Comfortable AC Vehicle Fleet Ready for Departure",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1080,
    "height": 1080,
    "aspectRatio": 1,
    "isFeatured": false
  },
  {
    "id": 26,
    "src": "/gallery/tripsthan-img-26.jpg",
    "fileName": "tripsthan-img-26.jpg",
    "originalName": "Image-41879.jpg.jpeg",
    "title": "Historic Stepwell (Baori) Architecture",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1080,
    "height": 810,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 27,
    "src": "/gallery/tripsthan-img-27.jpg",
    "fileName": "tripsthan-img-27.jpg",
    "originalName": "IMG_20240315_182855.jpg.jpeg",
    "title": "Sunset Panorama Over Royal Palace Grounds",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 3000,
    "height": 4000,
    "aspectRatio": 0.75,
    "isFeatured": true
  },
  {
    "id": 28,
    "src": "/gallery/tripsthan-img-28.jpg",
    "fileName": "tripsthan-img-28.jpg",
    "originalName": "IMG-20230327-WA0004.jpg.jpeg",
    "title": "Chauffeur Greeting Guests with Traditional Warmth",
    "category": "Luxury Fleet & Cabs",
    "location": "North India Circuits",
    "width": 1200,
    "height": 1599,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 29,
    "src": "/gallery/tripsthan-img-29.jpg",
    "fileName": "tripsthan-img-29.jpg",
    "originalName": "IMG-20240513-WA0000.jpg.jpeg",
    "title": "Smooth Highway Journey on Yamuna Expressway",
    "category": "Luxury Fleet & Cabs",
    "location": "North India Circuits",
    "width": 817,
    "height": 1089,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 30,
    "src": "/gallery/tripsthan-img-30.jpg",
    "fileName": "tripsthan-img-30.jpg",
    "originalName": "IMG-20260305-WA0002.jpg.jpeg",
    "title": "Guest Couple Photo at Scenic Heritage Landmark",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1200,
    "height": 1600,
    "aspectRatio": 0.75,
    "isFeatured": true
  },
  {
    "id": 31,
    "src": "/gallery/tripsthan-img-31.jpg",
    "fileName": "tripsthan-img-31.jpg",
    "originalName": "IMG-20260306-WA0003.jpg.jpeg",
    "title": "Historic Mausoleum & Red Sandstone Courtyard",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1200,
    "height": 1600,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 32,
    "src": "/gallery/tripsthan-img-32.jpg",
    "fileName": "tripsthan-img-32.jpg",
    "originalName": "IMG-20260306-WA0006.jpg.jpeg",
    "title": "Royal Elephant & Haveli Gate Entrance",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1200,
    "height": 1600,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 33,
    "src": "/gallery/tripsthan-img-33.jpg",
    "fileName": "tripsthan-img-33.jpg",
    "originalName": "IMG-20260308-WA0008.jpg.jpeg",
    "title": "Scenic Village Life & Heritage Trails",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1098,
    "height": 1600,
    "aspectRatio": 0.69,
    "isFeatured": false
  },
  {
    "id": 34,
    "src": "/gallery/tripsthan-img-34.jpg",
    "fileName": "tripsthan-img-34.jpg",
    "originalName": "IMG-20260308-WA0009.jpg.jpeg",
    "title": "Luxury Traveler Group at Heritage Hotel",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1148,
    "height": 1600,
    "aspectRatio": 0.72,
    "isFeatured": false
  },
  {
    "id": 35,
    "src": "/gallery/tripsthan-img-35.jpg",
    "fileName": "tripsthan-img-35.jpg",
    "originalName": "jj.jpg.jpeg",
    "title": "Pristine Private Cab Interiors & Sanitized Rides",
    "category": "Luxury Fleet & Cabs",
    "location": "North India Circuits",
    "width": 1200,
    "height": 900,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 36,
    "src": "/gallery/tripsthan-img-36.jpg",
    "fileName": "tripsthan-img-36.jpg",
    "originalName": "Messenger_creation_7F5B6304-CB13-4EF6-8D04-92892F0AADF8.jpeg",
    "title": "Exploring Local Art, Crafts & Marble Inlay",
    "category": "Guest Experiences",
    "location": "Golden Triangle & Beyond",
    "width": 1536,
    "height": 2048,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 37,
    "src": "/gallery/tripsthan-img-37.jpg",
    "fileName": "tripsthan-img-37.jpg",
    "originalName": "photo2jpg.jpg.jpeg",
    "title": "Scenic Lake View Palace in Udaipur",
    "category": "Tours & Highlights",
    "location": "Rajasthan & Golden Triangle",
    "width": 1200,
    "height": 1200,
    "aspectRatio": 1,
    "isFeatured": false
  },
  {
    "id": 38,
    "src": "/gallery/tripsthan-img-38.jpg",
    "fileName": "tripsthan-img-38.jpg",
    "originalName": "Screenshot_20260101_095833_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Royal Rajasthan",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1080,
    "height": 1362,
    "aspectRatio": 0.79,
    "isFeatured": false
  },
  {
    "id": 39,
    "src": "/gallery/tripsthan-img-39.jpg",
    "fileName": "tripsthan-img-39.jpg",
    "originalName": "Screenshot_20260101_095841_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Taj Mahal Wonder",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1080,
    "height": 818,
    "aspectRatio": 1.32,
    "isFeatured": false
  },
  {
    "id": 40,
    "src": "/gallery/tripsthan-img-40.jpg",
    "fileName": "tripsthan-img-40.jpg",
    "originalName": "Screenshot_20260101_095858_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Jaipur Forts",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1079,
    "height": 1348,
    "aspectRatio": 0.8,
    "isFeatured": false
  },
  {
    "id": 41,
    "src": "/gallery/tripsthan-img-41.jpg",
    "fileName": "tripsthan-img-41.jpg",
    "originalName": "Screenshot_20260101_095935_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Delhi Heritage",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1080,
    "height": 778,
    "aspectRatio": 1.39,
    "isFeatured": false
  },
  {
    "id": 42,
    "src": "/gallery/tripsthan-img-42.jpg",
    "fileName": "tripsthan-img-42.jpg",
    "originalName": "Screenshot_20260101_095950_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Mountain Escape",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1080,
    "height": 1362,
    "aspectRatio": 0.79,
    "isFeatured": false
  },
  {
    "id": 43,
    "src": "/gallery/tripsthan-img-43.jpg",
    "fileName": "tripsthan-img-43.jpg",
    "originalName": "Screenshot_20260101_100003_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Varanasi Boat Ride",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1080,
    "height": 1358,
    "aspectRatio": 0.8,
    "isFeatured": false
  },
  {
    "id": 44,
    "src": "/gallery/tripsthan-img-44.jpg",
    "fileName": "tripsthan-img-44.jpg",
    "originalName": "Screenshot_20260101_100009_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Desert Safari Sunset",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1080,
    "height": 826,
    "aspectRatio": 1.31,
    "isFeatured": false
  },
  {
    "id": 45,
    "src": "/gallery/tripsthan-img-45.jpg",
    "fileName": "tripsthan-img-45.jpg",
    "originalName": "Screenshot_20260101_100016_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Royal Haveli Charm",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1080,
    "height": 1359,
    "aspectRatio": 0.79,
    "isFeatured": false
  },
  {
    "id": 46,
    "src": "/gallery/tripsthan-img-46.jpg",
    "fileName": "tripsthan-img-46.jpg",
    "originalName": "Screenshot_20260101_100022_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Chauffeur Journey",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1077,
    "height": 1077,
    "aspectRatio": 1,
    "isFeatured": false
  },
  {
    "id": 47,
    "src": "/gallery/tripsthan-img-47.jpg",
    "fileName": "tripsthan-img-47.jpg",
    "originalName": "Screenshot_20260101_100032_Instagram.jpg.jpeg",
    "title": "Instagram Traveler Highlight: Vibrant Indian Colors",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1065,
    "height": 1085,
    "aspectRatio": 0.98,
    "isFeatured": false
  },
  {
    "id": 48,
    "src": "/gallery/tripsthan-img-48.jpg",
    "fileName": "tripsthan-img-48.jpg",
    "originalName": "tarde-de-cine-en-indilo.jpg.jpeg",
    "title": "Cultural Cinema & Travel Celebration in India",
    "category": "Culture & Sightseeing",
    "location": "Delhi, Jaipur & Varanasi",
    "width": 1200,
    "height": 900,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 49,
    "src": "/gallery/tripsthan-img-49.jpg",
    "fileName": "tripsthan-img-49.jpg",
    "originalName": "tripsthancom (1).jpg.jpeg",
    "title": "TripSthan Signature Tour: Delhi to Agra Express",
    "category": "Luxury Fleet & Cabs",
    "location": "North India Circuits",
    "width": 1100,
    "height": 1467,
    "aspectRatio": 0.75,
    "isFeatured": true
  },
  {
    "id": 50,
    "src": "/gallery/tripsthan-img-50.jpg",
    "fileName": "tripsthan-img-50.jpg",
    "originalName": "tripsthancom (2).jpg.jpeg",
    "title": "TripSthan Signature Tour: Jaipur Heritage Day",
    "category": "Luxury Fleet & Cabs",
    "location": "North India Circuits",
    "width": 1200,
    "height": 900,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 51,
    "src": "/gallery/tripsthan-img-51.jpg",
    "fileName": "tripsthan-img-51.jpg",
    "originalName": "tripsthancom (3).jpg.jpeg",
    "title": "TripSthan Signature Tour: Golden Triangle Circuit",
    "category": "Luxury Fleet & Cabs",
    "location": "North India Circuits",
    "width": 1200,
    "height": 675,
    "aspectRatio": 1.78,
    "isFeatured": false
  },
  {
    "id": 52,
    "src": "/gallery/tripsthan-img-52.jpg",
    "fileName": "tripsthan-img-52.jpg",
    "originalName": "tripsthancom (4).jpg.jpeg",
    "title": "TripSthan Signature Tour: Private AC Fleet Lineup",
    "category": "Luxury Fleet & Cabs",
    "location": "North India Circuits",
    "width": 1200,
    "height": 861,
    "aspectRatio": 1.39,
    "isFeatured": false
  },
  {
    "id": 53,
    "src": "/gallery/tripsthan-img-53.jpg",
    "fileName": "tripsthan-img-53.jpg",
    "originalName": "tripsthancom (6).jpg.jpeg",
    "title": "TripSthan Signature Tour: Royal Rajasthan Safari",
    "category": "Luxury Fleet & Cabs",
    "location": "North India Circuits",
    "width": 1200,
    "height": 900,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 54,
    "src": "/gallery/tripsthan-img-54.jpg",
    "fileName": "tripsthan-img-54.jpg",
    "originalName": "tripsthancom.jpg.jpeg",
    "title": "TripSthan Premium Chauffeur Car at Monument Gate",
    "category": "Luxury Fleet & Cabs",
    "location": "North India Circuits",
    "width": 1100,
    "height": 1467,
    "aspectRatio": 0.75,
    "isFeatured": true
  },
  {
    "id": 55,
    "src": "/gallery/tripsthan-img-55.jpg",
    "fileName": "tripsthan-img-55.jpg",
    "originalName": "WhatsApp Image 2026-04-27 at 11.59.25 (1).jpeg",
    "title": "Happy Family Tour Memory with TripSthan Chauffeur",
    "category": "Culture & Sightseeing",
    "location": "Delhi, Jaipur & Varanasi",
    "width": 960,
    "height": 1280,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 56,
    "src": "/gallery/tripsthan-img-56.jpg",
    "fileName": "tripsthan-img-56.jpg",
    "originalName": "WhatsApp Image 2026-04-27 at 11.59.25.jpeg",
    "title": "On-the-Road Rest Stop & Refreshments in Rajasthan",
    "category": "Culture & Sightseeing",
    "location": "Delhi, Jaipur & Varanasi",
    "width": 1200,
    "height": 1600,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 57,
    "src": "/gallery/tripsthan-img-57.jpg",
    "fileName": "tripsthan-img-57.jpg",
    "originalName": "WhatsApp Image 2026-04-27 at 11.59.26.jpeg",
    "title": "VIP Travelers Exploring the Palaces of Rajasthan",
    "category": "Culture & Sightseeing",
    "location": "Delhi, Jaipur & Varanasi",
    "width": 1600,
    "height": 1200,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 58,
    "src": "/gallery/tripsthan-img-58.jpg",
    "fileName": "tripsthan-img-58.jpg",
    "originalName": "WhatsApp Image 2026-04-27 at 11.59.28 (1).jpeg",
    "title": "Chauffeur Assisted Sightseeing & Guided Walk",
    "category": "Culture & Sightseeing",
    "location": "Delhi, Jaipur & Varanasi",
    "width": 1600,
    "height": 1200,
    "aspectRatio": 1.33,
    "isFeatured": false
  },
  {
    "id": 59,
    "src": "/gallery/tripsthan-img-59.jpg",
    "fileName": "tripsthan-img-59.jpg",
    "originalName": "WhatsApp Image 2026-04-27 at 11.59.32.jpeg",
    "title": "Comfortable Traveler Transit Between Cities",
    "category": "Culture & Sightseeing",
    "location": "Delhi, Jaipur & Varanasi",
    "width": 1200,
    "height": 1600,
    "aspectRatio": 0.75,
    "isFeatured": false
  },
  {
    "id": 60,
    "src": "/gallery/tripsthan-img-60.jpg",
    "fileName": "tripsthan-img-60.jpg",
    "originalName": "wonderful-tours-in-agra (1).jpg.jpeg",
    "title": "Wonderful Tours in Agra: Taj Mahal Guided Visit",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1200,
    "height": 1200,
    "aspectRatio": 1,
    "isFeatured": true
  },
  {
    "id": 61,
    "src": "/gallery/tripsthan-img-61.jpg",
    "fileName": "tripsthan-img-61.jpg",
    "originalName": "wonderful-tours-in-agra.jpg.jpeg",
    "title": "Wonderful Tours in Agra: Red Fort & Mehtab Bagh",
    "category": "Heritage & Palaces",
    "location": "Agra & Rajasthan",
    "width": 1200,
    "height": 1200,
    "aspectRatio": 1,
    "isFeatured": true
  }
];

export default GALLERY_ITEMS;
